---
title: "625 Project"
output: pdf_document
date: "2023-11-02"
---

```{r}
library(haven)
library(tidyverse)
birthweight=read_xpt("P_ECQ.XPT")
demo=read_xpt("P_DEMO.XPT")
activity=read_xpt("P_PAQY.XPT")
diet=read_xpt("P_DBQ.XPT")
foodsec=read_xpt("P_FSQ.XPT")
body=read_xpt("P_BMX.XPT")

```


```{r}
df_list=list(birthweight,demo,activity,diet,foodsec,body)
data=df_list%>%reduce(inner_join,by='SEQN')
data=subset(data, select=c(SEQN,ECQ020,ECD070A,ECD070B,RIAGENDR,RIDAGEYR,FSDHH,BMXWT,BMXBMI,PAQ706,DBD900,
                           RIDRETH3,WHQ030E))
colnames(data)=c("SEQN","smoke","birth_pounds","birth_ounces","sex","age","food_sec","weight",
                 "bmi","activity","fastfood","race","perception")
```



```{r}
#adding na for 9999
data$birth_pounds[data$birth_pounds==9999]=NA
data$birth_ounces[data$birth_ounces==9999]=NA

#changing weight to pounds
data$weight_pd=NA
for (i in 1:3970) {
  if (!is.na(data$weight[i])) {
    data$weight_pd[i]=data$weight[i]*2.205
  }
}

#combining birth pounds and birth ounces
data$birthweight=NA
for (i in 1:3970) {
  if (!is.na(data$birth_pounds[i])) {
    if (!is.na(data$birth_ounces[i])) {
      if (data$birth_ounces[i]==0) {
        data$birthweight[i]=data$birth_pounds[i]
      } else {
        data$birthweight[i]=data$birth_pounds[i]+(data$birth_ounces[i]/16)
      }
    }
  }
}

#fixes smoke
data$smoke[data$smoke==9]=NA
data$smoke[data$smoke==7]=NA

#changing birthweight to kg
data$birthweight_kg=NA
for (i in 1:3970) {
  if (!is.na(data$birthweight[i])) {
    data$birthweight_kg[i]=data$birthweight[i]/2.205
  }
}

#fixing activity na
data$activity[data$activity==99]=NA

#fixing fastfood
data$fastfood[data$fastfood==9999]=NA
data$fastfood[data$fastfood==5555]=22

#fixing perception
data$perception[data$perception==9]=NA



```

```{r}
data$percentile=NA
data$zscore=NA
#for boys under 95th percentile
for (i in 1:3970) {
  if (data$sex[i]==1) {
    if (!is.na(data$bmi[i])) {
      if (data$age[i]==2 && data$bmi[i]<=19.2789) {
        data$zscore[i]=(((data$bmi[i]/16.548)^(-1.982))-1)/(-1.982*0.0801)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==3 && data$bmi[i]<=18.2384) {
        data$zscore[i]=(((data$bmi[i]/16)^(-1.42))-1)/(-1.42*0.0726)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==4 && data$bmi[i]<=17.8361) {
        data$zscore[i]=(((data$bmi[i]/15.628)^(-1.715))-1)/(-1.715*0.0719)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==5 && data$bmi[i]<=17.9) {
        data$zscore[i]=(((data$bmi[i]/15.419)^(-2.615))-1)/(-2.615*0.076)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==6 && data$bmi[i]<=18.4142) {
        data$zscore[i]=(((data$bmi[i]/15.384)^(-3.212))-1)/(-3.212*0.083)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==7 && data$bmi[i]<=19.1524) {
        data$zscore[i]=(((data$bmi[i]/15.513)^(-3.323))-1)/(-3.323*0.0921)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==8 && data$bmi[i]<=20.0) {
        data$zscore[i]=(((data$bmi[i]/15.782)^(-3.183))-1)/(-3.183*0.102)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==9 && data$bmi[i]<=21.1) {
        data$zscore[i]=(((data$bmi[i]/16.167)^(-2.971))-1)/(-2.971*0.112)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==10 && data$bmi[i]<=22.15) {
        data$zscore[i]=(((data$bmi[i]/16.646)^(-2.766))-1)/(-2.766*0.12)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==11 && data$bmi[i]<=23.21) {
        data$zscore[i]=(((data$bmi[i]/17.2)^(-2.59))-1)/(-2.59*0.1267)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==12 && data$bmi[i]<=24.23) {
        data$zscore[i]=(((data$bmi[i]/17.815)^(-2.447))-1)/(-2.447*0.131)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==13 && data$bmi[i]<=25.18) {
        data$zscore[i]=(((data$bmi[i]/18.472)^(-2.329))-1)/(-2.329*0.134)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==14 && data$bmi[i]<=26.05) {
        data$zscore[i]=(((data$bmi[i]/19.158)^(-2.227))-1)/(-2.227*0.135)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==15 && data$bmi[i]<=26.837) {
        data$zscore[i]=(((data$bmi[i]/19.858)^(-2.132))-1)/(-2.132*0.135)
        data$percentile[i]=pnorm(data$zscore[i])*100
      }  
    }
  }
}

```

```{r}
#for boys above 95th percentile
for (i in 1:3970) {
  if (is.na(data$percentile[i])) {
    if (data$sex[i]==1) {
      if (!is.na(data$bmi[i])) {
        if (data$age[i]==2) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-19.2789)/1.396)
        } else if (data$age[i]==3) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-18.2384)/1.869)
        } else if (data$age[i]==4) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-17.8361)/2.324)
        } else if (data$age[i]==5) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-17.9389)/2.761)
        } else if (data$age[i]==6) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-18.4142)/3.18)
        } else if (data$age[i]==7) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-19.1524)/3.58)
        } else if (data$age[i]==8) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-20.0679)/3.963)
        } else if (data$age[i]==9) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-21.0889)/4.327)
        } else if (data$age[i]==10) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-22.1541)/4.673)
        } else if (data$age[i]==11) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-23.2136)/5.00)
        } else if (data$age[i]==12) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-24.2298)/5.31)
        } else if (data$age[i]==13) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-25.1781)/5.601)
        } else if (data$age[i]==14) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-26.0466)/5.875)
        } else if (data$age[i]==15) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-26.8369)/6.13)
        }
      }
    }
  }
}

```


```{r}
#for girls under 95th percentile
for (i in 1:3970) {
  if (data$sex[i]==2) {
    if (!is.na(data$bmi[i])) {
      if (data$age[i]==2 && data$bmi[i]<=19.06) {
        data$zscore[i]=(((data$bmi[i]/16.388)^(-1.024))-1)/(-1.024*0.085)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==3 && data$bmi[i]<=18.25) {
        data$zscore[i]=(((data$bmi[i]/15.699)^(-2.097))-1)/(-2.097*0.0786)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==4 && data$bmi[i]<=18.03) {
        data$zscore[i]=(((data$bmi[i]/15.299)^(-3.019))-1)/(-3.019*0.0787)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==5 && data$bmi[i]<=18.26) {
        data$zscore[i]=(((data$bmi[i]/15.152)^(-3.35))-1)/(-3.35*0.0843)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==6 && data$bmi[i]<=18.84) {
        data$zscore[i]=(((data$bmi[i]/15.217)^(-3.225))-1)/(-3.225*0.0938)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==7 && data$bmi[i]<=19.68) {
        data$zscore[i]=(((data$bmi[i]/15.454)^(-2.926))-1)/(-2.926*0.105)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==8 && data$bmi[i]<=20.7) {
        data$zscore[i]=(((data$bmi[i]/15.827)^(-2.617))-1)/(-2.617*0.117)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==9 && data$bmi[i]<=21.82) {
        data$zscore[i]=(((data$bmi[i]/16.306)^(-2.361))-1)/(-2.361*0.128)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==10 && data$bmi[i]<=22.98) {
        data$zscore[i]=(((data$bmi[i]/16.862)^(-2.171))-1)/(-2.171*0.137)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==11 && data$bmi[i]<=24.14) {
        data$zscore[i]=(((data$bmi[i]/17.469)^(-2.045))-1)/(-2.045*0.144)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==12 && data$bmi[i]<=25.26) {
        data$zscore[i]=(((data$bmi[i]/18.101)^(-1.976))-1)/(-1.976*0.148)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==13 && data$bmi[i]<=26.3) {
        data$zscore[i]=(((data$bmi[i]/18.736)^(-1.955))-1)/(-1.955*0.151)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==14 && data$bmi[i]<=27.25) {
        data$zscore[i]=(((data$bmi[i]/19.353)^(-1.977))-1)/(-1.977*0.151)
        data$percentile[i]=pnorm(data$zscore[i])*100
      } else if (data$age[i]==15 && data$bmi[i]<=28.124) {
        data$zscore[i]=(((data$bmi[i]/19.931)^(-2.035))-1)/(-2.035*0.151)
        data$percentile[i]=pnorm(data$zscore[i])*100
      }  
    }
  }
}
```


```{r}
#for girls above 95th percentile
for (i in 1:3970) {
  if (is.na(data$percentile[i])) {
    if (data$sex[i]==2) {
      if (!is.na(data$bmi[i])) {
        if (data$age[i]==2) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-19.0582)/1.587)
        } else if (data$age[i]==3) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-18.2548)/1.952)
        } else if (data$age[i]==4) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-18.0285)/2.316)
        } else if (data$age[i]==5) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-18.2574)/2.677)
        } else if (data$age[i]==6) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-18.8378)/3.036)
        } else if (data$age[i]==7) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-19.6779)/3.393)
        } else if (data$age[i]==8) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-20.6953)/3.747)
        } else if (data$age[i]==9) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-21.8173)/4.01)
        } else if (data$age[i]==10) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-22.9826)/4.45)
        } else if (data$age[i]==11) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-24.1414)/4.798)
        } else if (data$age[i]==12) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-25.2556)/5.144)
        } else if (data$age[i]==13) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-26.299)/5.487)
        } else if (data$age[i]==14) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-27.256)/5.829)
        } else if (data$age[i]==15) {
          data$percentile[i]=90+10*pnorm((data$bmi[i]-28.1237)/6.168)
        }
      }
    }
  }
}
```

```{r}
plot(data$race,data$percentile)
plot(data$smoke,data$percentile)
plot(data$food_sec,data$percentile)
plot(data$food_sec,data$percentile)
plot(data$activity,data$percentile)
plot(data$perception,data$percentile)

```


```{r}
data$smoke=factor(data$smoke)
data$activity=factor(data$activity)
data$sex=factor(data$sex)
data$food_sec=factor(data$food_sec)
data$race=factor(data$race)
data$perception=factor(data$perception)
model=lm(percentile~smoke+birthweight+food_sec+activity+sex+fastfood+race,data=data)
summary(model)
```




