---
title: "625 Project model fit"
output: pdf_document
date: "2023-11-02"
---

```{r}
library(haven)
library(tidyverse)
library(dplyr)
birthweight=read_xpt("P_ECQ.XPT")
demo=read_xpt("P_DEMO.XPT")
activity=read_xpt("P_PAQY.XPT")
diet=read_xpt("P_DBQ.XPT")
foodsec=read_xpt("P_FSQ.XPT")
body=read_xpt("P_BMX.XPT")

```

```{r}
#Load the clean data resulting from 625 Project Data Cleaning.Rmd
data <- readRDS('clean_data.RDS')

#Change the reference of race to white americans
data$race <- factor(data$race, levels = c(3, 1,2,4,5,6,7))

#Categorize activity into levels
data$activity1 <- as.character(data$activity)
data <- data %>%
  mutate(activity1 = case_when(
    activity1 =='0' ~ "0",
    activity1 =='1' ~ "1-3",
    activity1 =='2' ~ "1-3",
    activity1 =='3' ~ "1-3",
    activity1 =='4' ~ "4-6",
    activity1 =='5' ~ "4-6",
    activity1 =='6' ~ "4-6",
    activity1 =='7' ~ "7",
  ))

data$activity1 <- as.factor(data$activity1)
data
```

```{r}
#Fit a linear regressiion model with the predictors we found from EDA
m1 <- lm(sqrt(growth_percentile) ~ sex+race+birthweight+smoke+food_sec+fastfood+activity1, data=data)
summary(m1)
AIC(m1)
plot(m1$residuals)
```

```{r}
#check for potential interactions by plotting response and predictors filled by levels of sex
ggplot(data, aes(x=race, y=growth_percentile, fill=sex)) + 
    geom_boxplot()
ggplot(data, aes(x=birthweight, y=growth_percentile, fill=sex)) + 
    geom_boxplot()
ggplot(data, aes(x=smoke, y=growth_percentile, fill=sex)) + 
    geom_boxplot()

#It seems that there is potential interaction between food security and sex
ggplot(data, aes(x=food_sec, y=growth_percentile, fill=sex)) + 
    geom_boxplot()

ggplot(data, aes(x=fastfood, y=growth_percentile, fill=sex)) + 
    geom_boxplot()
ggplot(data, aes(x=activity1, y=growth_percentile, fill=sex)) + 
    geom_boxplot()
```

```{r}
#linear regression model with interaction sex*food security
m2 <- lm(growth_percentile ~ sex+race+birthweight+smoke+food_sec+fastfood+activity1+sex*food_sec, data=data)
summary(m2)
AIC(m2)
plot(m2, which=2)

#After checking diagnostic plots of m2, normal qq plot does not follow straight line
#Added in transformation for normal distributed residuals
m3 <- lm(sqrt(growth_percentile) ~ sex+race+birthweight+smoke+food_sec+fastfood+activity1+sex*food_sec, data=data)
summary(m3)
AIC(m3)
plot(m3)

#nrow(data)
#nrow(model.matrix(m1))
#nrow(model.matrix(m3))
#anova(m3,m1)
```

```{r}
plot(m2)
plot(m1)
```
```{r}
qqnorm(residuals(m2))
qqline(residuals(m2))
```

```{r}
#Logistic regression for obesity binary variable using predictors resulting from linear regression analysis
#Make obesity binary variable (>= 95 BMI percentile is considered obese)
data <- data %>%
  mutate(growth_percentile1 = case_when(
    growth_percentile < 95 ~ 0,
    growth_percentile >= 95 ~ 1
  ))

data$growth_percentile1 <- as.factor(data$growth_percentile1)
data

#Fit logistic regression model
m4 <- glm(growth_percentile1 ~ race+birthweight+smoke+food_sec+fastfood+activity1, data = data, family = binomial)
summary(m4)
AIC(m4)
plot(m4)

#check diagnostics cooks distance
cooks_distance <- cooks.distance(m4)
plot(cooks_distance, pch = 20, main = "Cook's Distance Plot")

#VIF values
library(car)
#crPlots(m4)
vif(m4)

#Deviance residuals plots
deviance_residuals <- residuals(m4, type = "deviance")
plot(predict(m4, type = "response"), deviance_residuals, 
     ylab = "Deviance Residuals", xlab = "Fitted Values")

```

